# Generated by Django 5.2.7 on 2025-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='password123', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
