# Generated by Django 5.2.7 on 2025-11-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_person_password_alter_person_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
