# Generated by Django 5.2.7 on 2026-02-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_person_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('economy_seats', models.IntegerField(default=60)),
                ('business_seats', models.IntegerField(default=30)),
                ('economy_price', models.IntegerField()),
                ('business_price', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
    ]
