# Generated by Django 5.2.7 on 2026-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('airport_code', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
