# Generated by Django 5.2.7 on 2026-02-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField()),
                ('economy_seats_total', models.IntegerField()),
                ('economy_seats_available', models.IntegerField()),
                ('business_seats_total', models.IntegerField()),
                ('business_seats_available', models.IntegerField()),
            ],
        ),
    ]
