# Generated by Django 5.2.7 on 2026-03-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='business_seats_total',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='economy_seats_total',
        ),
    ]
